"""added_currency_field_to_offermodel

Revision ID: 16f5ad85c442
Revises: 9a040ff26e4b
Create Date: 2026-02-17 12:35:09.178550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f5ad85c442'
down_revision: Union[str, Sequence[str], None] = '9a040ff26e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('currency', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE offers SET currency = 'EUR' WHERE currency IS NULL")
    op.alter_column("offers", "currency", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'currency')
    # ### end Alembic commands ###
