"""added_default_roles_extended_fields

Revision ID: 7810a3cca48e
Revises: 2f5ab0af4028
Create Date: 2026-01-22 15:48:35.432744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7810a3cca48e'
down_revision: Union[str, Sequence[str], None] = '2f5ab0af4028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('prices', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
    op.add_column('users', sa.Column('role', sa.String(length=60), server_default='manager', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.alter_column('prices', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('prices', 'name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
