"""add_email_message_id_to_prices

Revision ID: 7e1eded8d7aa
Revises: 7810a3cca48e
Create Date: 2026-01-26 11:32:22.357467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1eded8d7aa'
down_revision: Union[str, Sequence[str], None] = '7810a3cca48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('email_message_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_prices_email_message_id'), 'prices', ['email_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_email_message_id'), table_name='prices')
    op.drop_column('prices', 'email_message_id')
    # ### end Alembic commands ###
