"""prices: add source_type, email_message_id, unique art+source

Revision ID: ce9482466602
Revises: 7e1eded8d7aa
Create Date: 2026-02-06 15:12:38.452671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9482466602'
down_revision: Union[str, Sequence[str], None] = '7e1eded8d7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_price_art_source', 'prices', ['art', 'source'])
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bitrix_user_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['tg_id'])
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'bitrix_user_id')
    op.drop_column('users', 'tg_id')
    op.drop_constraint('uq_price_art_source', 'prices', type_='unique')
    # ### end Alembic commands ###
