"""add username to users

Revision ID: de730523fed5
Revises: ce9482466602
Create Date: 2026-02-12 11:35:33.947548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de730523fed5'
down_revision: Union[str, Sequence[str], None] = 'ce9482466602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_generations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_generations_deal_id'), 'pdf_generations', ['deal_id'], unique=False)
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    # заполняем старые строки
    op.execute("UPDATE users SET username = 'unknown' WHERE username IS NULL")

    # делаем NOT NULL
    op.alter_column("users", "username", nullable=False)

    op.alter_column('users', 'tg_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'bitrix_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bitrix_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'tg_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'username')
    op.drop_index(op.f('ix_pdf_generations_deal_id'), table_name='pdf_generations')
    op.drop_table('pdf_generations')
    # ### end Alembic commands ###
