"""add_ai_fields_to_offer_items

Revision ID: f24e199e50da
Revises: a9b8c7d6e5f4
Create Date: 2026-04-16 10:22:14.998864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f24e199e50da'
down_revision: Union[str, Sequence[str], None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_items', sa.Column('added_from', sa.String(length=20), nullable=True))
    op.add_column('offer_items', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('offer_items', sa.Column('confidence_level', sa.Float(), nullable=True))
    op.add_column('offer_items', sa.Column('analog_id', sa.Integer(), nullable=True))
    op.alter_column('offer_items', 'quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('offers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('offers', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('offers', 'is_generating',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'is_generating',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('offers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('offers', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('offers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('offer_items', 'quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.drop_column('offer_items', 'analog_id')
    op.drop_column('offer_items', 'confidence_level')
    op.drop_column('offer_items', 'reason')
    op.drop_column('offer_items', 'added_from')
    # ### end Alembic commands ###
